# -*- coding: utf-8 -*-
"""FINAL PROJECT main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/190eK6TWAL1j0UGkV2hBETHSnLzgKGHqX
"""

#library instalation
!pip install mysql-connector-python

import mysql.connector
from preparation import *
from queries import *
from db_config import *

# function to create db

#create_db(dbconfig_ich_temp)

# create_table - create a new table for write

#create_table(dbconfig_ich)

# run the programm

while True:
    choose = input("Search by name - 1, search by year and genre - 2, search by actor - 3, finish programm - 4, most common - 9: ")
    if choose == '1':
        name = str(input('Insert movie name or part of movie name:')).lower().strip()
        search_by_name(dbconfig_amazon, dbconfig_ich, name)
    elif choose == '2':
        genre = str(input('Insert genre of the movie you would like to search:')).lower().strip()
        year = str(input('Insert age of the movie production you would like to search:')).strip()
        search_by_year_genre(dbconfig_amazon, dbconfig_ich, genre, year)
    elif choose == '3':
        actor = str(input('Insert name of the actor:')).strip().title()
        search_by_actor(dbconfig_amazon, dbconfig_ich, actor)
    elif choose == '4':
        print('Programm is closed')
        break
    elif choose == '9':
        get_common(dbconfig_ich)
    else:
        print("Make your choise, insert 1, 2, 3, 4 or 9")